id: IF1B5D221
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:53:45+00:00'
last_modified: '2022-06-07T12:09:14.998527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5774
  title: ཧོར་གྱི་ཆོས་འབྱུང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5CD0:
      image_group_id: I1KG5782
      title: Volume 1 of hor gyi chos 'byung
      total_pages: 248
      order: 1
      base_file: 5CD0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
